### ISSUE TITLE
add source file verification/quality check

### ISSUE THREAD

**Issue by sbsimo** [ITHACA-org/gpm-accumul#4]
Typical case: a GPM source file is corrupted/broken after download. Not sure about the root cause, may be connection interruption. After that the procedure ends with error and keeps that error, stopping the entire service, for a period equal to the accumulation period (in our case is 96h).

Potential solutions, starting from the easiest:

1. check every source file after download, by trying to open it with h5py library and verify the data structure. In case the verification fails, delete the source file
2. equal to previous case, and add re-iteration of download and check for a number n of times (3?)
3. equal to previous case, and allow for accumulation under certain conditions (e.g. number of missing measures lower than thresholds, 10% of total?)

NOTE: sample of broken file can be found in the production server, along with other source data (3B-HHR-E.MS.MRG.3IMERG.20180921-S203000-E205959.1230.V05B.RT-H5.bug)

**Comment by sbsimo** [comment]
checking can be done here https://github.com/ITHACA-org/gpm-accumul/blob/b84b2ebda0d1bfd331f4755f8378ec1cbde9c69a/erds.py#L24

as strategy, a method "is_corrupted" can be added here https://github.com/ITHACA-org/gpm-accumul/blob/b84b2ebda0d1bfd331f4755f8378ec1cbde9c69a/gpm_repo/gpm_wrapper.py#L67

ftpobj should track downloaded filenames, e.g. here https://github.com/ITHACA-org/gpm-accumul/blob/b84b2ebda0d1bfd331f4755f8378ec1cbde9c69a/gpm_repo/gpm_ftp.py#L98

**Comment by sbsimo** [comment]
implemented solution #5 
ongoing website monitoring

**Comment by njugunanduati** [comment]
hey am getting the 
    Mirroring FTP site
Traceback (most recent call last):
  File "erds.py", line 128, in <module>
    start()
  File "erds.py", line 118, in start
    mirror_gpm_site()
  File "erds.py", line 23, in mirror_gpm_site
    with GPMFTP() as ftp:
  File "/mnt/18C6A8720AFB9CA1/python/gpm-accumul/gpm_repo/gpm_ftp.py", line 18, in __init__
    super().__init__(self.GPM_HOST, user, passwd)
  File "/usr/local/lib/python3.6/ftplib.py", line 119, in __init__
    self.login(user, passwd, acct)
  File "/usr/local/lib/python3.6/ftplib.py", line 420, in login
    resp = self.sendcmd('PASS ' + passwd)
  File "/usr/local/lib/python3.6/ftplib.py", line 273, in sendcmd
    return self.getresp()
  File "/usr/local/lib/python3.6/ftplib.py", line 246, in getresp
    raise error_perm(resp)
ftplib.error_perm: 530 Login incorrect.

How do I get the ftp credentials?
Also where are this variables 
    from gpm_repo.credentials import THRESH_ADJ_ABSPATH, THRESHOLDS_ABSPATH
ImportError: cannot import name 'THRESH_ADJ_ABSPATH'

**Comment by paolamazzoglio** [comment]
You can create your credentials on https://registration.pps.eosdis.nasa.gov/registration/
Then, you will be able to download GPM IMERG half-hourly early run data using ftp://jsimpson.pps.eosdis.nasa.gov/NRTPUB/imerg/early/

If you are interested in the threshold methodology you can find additional information on www.mdpi.com/2072-4292/11/6/677
The methodology described in Section 2 and 3 will allow you to recreate these thresholds masks!
